apiVersion: apps/v1
kind: Deployment
metadata:
  name: valaxy-rtp
  namespace: valaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  valaxy-rtp
  template:
    metadata:
      labels:
        app:  valaxy-rtp
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  valaxy-rtp
        image: valaxy093.jfrog.io/valaxy-docker/ttrend:2.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        
