apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwOTMuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlVtVnphRzFoT2xKbGMyaHRZVUF4TWpNdUtnPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson